[[tg]]
arch = "aarch64"
git-tree-sha1 = "12189cc441a93d9fae376de779bdce6608b97ce8"
os = "macos"

    [[tg.download]]
    sha256 = "99dc7bd2cda5eba1f53eadc0b3b822f314883d714a6829fd4b3292d131bfb209"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.aarch64-apple-darwin.tar.gz"
[[tg]]
arch = "aarch64"
git-tree-sha1 = "5032ef3fb308c22c3d45b814af143b5149b23f3f"
libc = "glibc"
os = "linux"

    [[tg.download]]
    sha256 = "687e9e4816ad11d386d8d747af9459b3dbd3fc95da4a3cd1d5e434fe66fe5880"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.aarch64-linux-gnu.tar.gz"
[[tg]]
arch = "aarch64"
git-tree-sha1 = "7db33a80154ea6fa6a226d6c297c635692698e42"
libc = "musl"
os = "linux"

    [[tg.download]]
    sha256 = "cfae48b845bfa7cb6818ccd52dabb6ee63cab5fa26e37eec4ff1d93bb30ccf23"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.aarch64-linux-musl.tar.gz"
[[tg]]
arch = "aarch64"
git-tree-sha1 = "fca9ca225666a9ef99a211a64f1e28ff1b86babc"
os = "freebsd"

    [[tg.download]]
    sha256 = "96544a6149acc824bea0e577df9b76e8ec5ae364604165e21cdbf8a69d606bc7"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.aarch64-unknown-freebsd.tar.gz"
[[tg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a4a201445f318411d738432f66c0771b0a94e5e8"
libc = "glibc"
os = "linux"

    [[tg.download]]
    sha256 = "a059894cdda2a075e801d564e3695ed4647bcce023825b0be8e20959373cfdb3"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.armv6l-linux-gnueabihf.tar.gz"
[[tg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a977660644065e04bb472d950c90c4b49dee4f62"
libc = "musl"
os = "linux"

    [[tg.download]]
    sha256 = "2bfdb6d6d624ed1691d31d1f45fa76b38e49609704da094a114b561761964f84"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.armv6l-linux-musleabihf.tar.gz"
[[tg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c34f16e77c02a598338e4f22a6ad0b4e1e9a9671"
libc = "glibc"
os = "linux"

    [[tg.download]]
    sha256 = "85fc1f27d3c104a641a6a3a35a159e02a2b7311a396b8d0a8ac4e0aaab651b71"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.armv7l-linux-gnueabihf.tar.gz"
[[tg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c5f49efd3823883229bc45284c752875fbaa88d"
libc = "musl"
os = "linux"

    [[tg.download]]
    sha256 = "d7a75bffd1c37662197a6758caf6eccbdc3f65fa9fb4ceba1a3b784f442207a8"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.armv7l-linux-musleabihf.tar.gz"
[[tg]]
arch = "i686"
git-tree-sha1 = "ec4fb0e8ff59cb6dd3e4c7155c126d0215aec2ef"
libc = "glibc"
os = "linux"

    [[tg.download]]
    sha256 = "cfb50a04194c595a682b0d1be1e17c012ffa9b3bbff309368067149fe209e590"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.i686-linux-gnu.tar.gz"
[[tg]]
arch = "i686"
git-tree-sha1 = "7f6f2ec08e9c17cc9293a6a49cac60055f15aa82"
libc = "musl"
os = "linux"

    [[tg.download]]
    sha256 = "4ad73b4f026da4918e36aaa2466833ffe7219ed7750a0eb92f53adf9d762bca6"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.i686-linux-musl.tar.gz"
[[tg]]
arch = "i686"
git-tree-sha1 = "ae1afdbdf4be0501f7186ad7e6f78680ecbbd08f"
os = "windows"

    [[tg.download]]
    sha256 = "b456799cf2769d61557e76d2dd2636a00c0261efad4ab2c9d6f54c283580a1ca"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.i686-w64-mingw32.tar.gz"
[[tg]]
arch = "powerpc64le"
git-tree-sha1 = "3b737d099430efcb6779d0d6c03bc4e80112a077"
libc = "glibc"
os = "linux"

    [[tg.download]]
    sha256 = "209c283b69910277837e31f409b6ecb95451b9f60a88519ed228bb5b16776b1f"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.powerpc64le-linux-gnu.tar.gz"
[[tg]]
arch = "riscv64"
git-tree-sha1 = "20751489f44d65785c30b57bf30cbdbbe12ac5df"
libc = "glibc"
os = "linux"

    [[tg.download]]
    sha256 = "c73202db6f1a7ec9991b44a68447297f4090e3e10f48a2e40c2a9e895651f85c"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.riscv64-linux-gnu.tar.gz"
[[tg]]
arch = "x86_64"
git-tree-sha1 = "ed91c98d8501cc27a8f16e7ff5951db0d6123f36"
os = "macos"

    [[tg.download]]
    sha256 = "40bb6b115a69c189028796cccba5af2dba557ff0bd08ae22f999ec4a73619586"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.x86_64-apple-darwin.tar.gz"
[[tg]]
arch = "x86_64"
git-tree-sha1 = "35c7fe463d5fd9d9b7251a693ec14af1ab05587e"
libc = "glibc"
os = "linux"

    [[tg.download]]
    sha256 = "1e776cea16ef84eeb3910fba5f2c5e8808d72f6704ec964115dee4c3871242c2"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.x86_64-linux-gnu.tar.gz"
[[tg]]
arch = "x86_64"
git-tree-sha1 = "56d549e1b1ef0e42604cd89c08bbd1bfb890b5bd"
libc = "musl"
os = "linux"

    [[tg.download]]
    sha256 = "d7d1c14e2b4530823b0a2bd8d7653e6e26e111d0a42c9c7546025130a230b2ee"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.x86_64-linux-musl.tar.gz"
[[tg]]
arch = "x86_64"
git-tree-sha1 = "e2616b82ab2d8821a972c501f65efe0309860c72"
os = "freebsd"

    [[tg.download]]
    sha256 = "b29a88d617372ce18e9f3089d355e62b983de21ffc7744d3cf51f31de454be7b"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.x86_64-unknown-freebsd.tar.gz"
[[tg]]
arch = "x86_64"
git-tree-sha1 = "0f5c097f43028bc4b18fad34155ab739b811eb94"
os = "windows"

    [[tg.download]]
    sha256 = "c2c4d2839658b0f9417ce84c39fb36160a9348f4cd75896c7d5d110cdbfcd847"
    url = "https://github.com/JuliaBinaryWrappers/tg_jll.jl/releases/download/tg-v0.7.3+0/tg.v0.7.3.x86_64-w64-mingw32.tar.gz"
