# Autogenerated wrapper script for tg_jll for x86_64-apple-darwin
export libtg

JLLWrappers.@generate_wrapper_header("tg")
JLLWrappers.@declare_library_product(libtg, "@rpath/libtg.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtg,
        "lib/libtg.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
